services:
  app:
    image: doljanchi-invitation:latest
    container_name: doljanchi-invitation
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN_FILE: /run/secrets/telegram_bot_token
      TELEGRAM_CHAT_ID_FILE: /run/secrets/telegram_chat_id
    volumes:
      - media_data:/app/media
      - ${TELEGRAM_BOT_TOKEN_FILE_HOST:-/home/tnfwod/projects/cali-stackcheck/secrets/telegram_bot_token}:/run/secrets/telegram_bot_token:ro
      - ${TELEGRAM_CHAT_ID_FILE_HOST:-/home/tnfwod/projects/cali-stackcheck/secrets/invite_telegram_chat_id}:/run/secrets/telegram_chat_id:ro
    networks:
      - default
      - avocadoss_db_net
      - n8n_net

volumes:
  media_data:

networks:
  default:
  avocadoss_db_net:
    external: true
    name: avocadoss-wordpress_wp_network
  n8n_net:
    external: true
    name: n8n-server_n8n_net
