services:
  app:
    image: doljanchi-invitation:latest
    container_name: doljanchi-invitation
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - media_data:/app/media
    networks:
      - default
      - avocadoss_db_net

volumes:
  media_data:

networks:
  default:
  avocadoss_db_net:
    external: true
    name: avocadoss-wordpress_wp_network
